data:
  wine_red:
    dataset_name: WineQuality red
    file_path: winequality/winequality-red.csv
    target_name: quality
    target_index: 11
    target_class: 1
    multiclass_target: True
    predictor_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    multiclass_threshold: 6
    separator: ";"

  wine_white:
    dataset_name: WineQuality white
    file_path: winequality/winequality-white.csv
    target_name: quality
    target_index: 11
    target_class: 1
    multiclass_target: True
    predictor_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    multiclass_threshold: 6
    separator: ";"

  diabetes:
    dataset_name: Pima Indians Diabetes
    file_path: diabetes.csv
    target_name: Outcome
    target_index: 8
    target_class: 0
    predictor_indices: [0, 1, 2, 3, 4, 5, 6, 7]
    multiclass_target: False
    separator: ","

evaluation:
  params:
    classifier: # Possible values: sklearn, tensorflow
      - sklearn
      #- tensorflow 

    imputation_type:
      - mean
      - multiple

    ind_missing:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7

    num_missing:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7

    n:
      - 1
      - 5
      - 10
      - 20
      - 40
      - 80
      - 100
    k:
      - 3

  current_params:
    classifier:
      None
    
    ind_missing:
      None

    num_missing:
      None

    imputation_type:
      None

    n:
      None
    
    k:
      None

  debug:
    #True
    False

  numeric_metrics:
    - n_vectors
    - avg_dist_from_original
    - diversity
    - count_diversity
    - diversity_missing_values
    - count_diversity_missing_values
    - avg_sparsity
    - num_missing
    
  boolean_metrics:
    - undesired_class

  runtime_metrics:
    - total
    - multiple_imputation
    - counterfactual_generation
    - filtering
    - selection

  metrics_for_histograms:
    - avg_dist_from_original
    - diversity
    - count_diversity
    - diversity_missing_values
    - count_diversity_missing_values
    - avg_sparsity